### ISSUE TITLE
SeekArc Infinite is possible?

### ISSUE THREAD

**Issue by maclacerda** [neild001/SeekArc#7]
Good morning, 

I wonder if you can make infinite SeekArc? 
For example, it would be 0-100, but the value was not reset when you arrive at 100 instead went to 101 and so on. 

I thank you for the help

**Comment by hitchan** [comment]
You can achieve this by keeping your own count with the seekbar interface. Just check and see if the current seek progress is greater or less then ++ or -- appropriately.
